version: '3'

services:
  webdb:
    build:
      context: .
      args:
        - MYSQL_DEBIAN_SYS_MAINT_PASSWORD=${MYSQL_DEBIAN_SYS_MAINT_PASSWORD}
    volumes:
      - ./website:/var/www/drupal
      - mysql-data:/var/lib/mysql
    ports:
      - "80:80"
    env_file:
      - .env
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mysql-data: